catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('books/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('authors/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
    path('my-books/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
]

local_library_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from datetime import date
import uuid


class Genre(models.Model):
    """ Model representation of a book genre. """
    name = models.CharField(
        max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        return self.name


class Language(models.Model):
    """ Model representation of a book language """
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        return self.name


class Book(models.Model):
    """ Model representation of a book (but not a specific copy of a book). """
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        'Author',
        on_delete=models.SET_NULL,
        null=True
    )
    summary = models.TextField(
        max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField(
        'ISBN', max_length=13, help_text='13 Charater <a href="htpps://isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(
        Genre,
        help_text='Select a genre for this book'
    )
    language = models.ForeignKey(
        'Language', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book-detail", kwargs={"pk": self.pk})

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    """
    Model representating a specific copy of a book
    (i.e. that can be borrowed from the library)
    """
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text='Unique ID for this particular book across library'
    )
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book avalibility',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return f'{self.pk} ({self.book.title})'

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


class Author(models.Model):
    """ Model representation of a books author """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse("author-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import (
    Book,
    Author,
    BookInstance,
    Genre
)

# Create your views here.


def index(request):
    """ View function for home page of site. """
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Avaliable books (status = 'a')
    num_instances_avaliable = BookInstance.objects.filter(
        status__exact='a'
    ).count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    # Number of visits to this view, as counted in session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    num_genres = Genre.objects.filter(
        name__contains='Sci'
    ).count()

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_avaliable': num_instances_avaliable,
        'num_authors': num_authors,
        'num_genres': num_genres,
        'num_visits': num_visits
    }

    return render(request, 'index.html', context=context)


class BookListView(generic.ListView):
    model = Book
    paginate_by = 10
    # your own name for the list as a template valiable
    context_object_name = 'my_book_list'
    # queryset = Book.objects.filter(title__icontains='war')[:5] # Get 5 books containing the war
    template_name = 'book_list.html'  # Specify your own template name/location


class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'book_detail.html'


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10
    context_object_name = 'authors'
    template_name = 'author_list.html'


class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'author_detail.html'


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

templates/author_detail.html
{% extends 'base_generic.html' %}

{% block content %}
  <h1>Author: {{ author }}</h1>
  <p class="text-muted">{% if author.date_of_birth %}{{ author.date_of_birth }} - {% endif %}{% if author.date_of_death %} {{ author.date_of_death }}{% endif %}</p>
{% endblock content %}

templates/author_list.html
{% extends 'base_generic.html' %}

{% block content %}
  <h1>Author's List</h1>
  {% if authors %}
    <ul>
      {% for author in authors %}
        <li>
          <a href="{% url 'author-detail' author.pk %}">{{ author }}</a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No Authors</p>
  {% endif %}
{% endblock content %}

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% block title %}
  <title>Local Library</title>
  {% endblock title %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
        {% block sidebar %}
          <ul class="sidebar-nav">
            <li>
              <a href="{% url 'index' %}">Home</a>
            </li>
            <li>
              <a href="{% url 'books' %}">All books</a>
            </li>
            <li>
              <a href="{% url 'authors' %}">All authors</a>
            </li>
                {% if not user.is_authenticated %}
                  <a href="{% url 'login' %}?next={{request.path}}">Login</a>
                {% else %}
                  <li>User: {{ user.get_username }}</li>
                  <li>
                    <a href="{% url 'my-borrowed' %}">My Books</a>
                  </li>
                  <li>
                    <a href="{% url 'logout' %}?next={{request.path}}">Logout</a>
                  </li>
                {% endif %}
          </ul>
        {% endblock sidebar %}
      </div><!--/.col-sm-2-->
      <div class="col-sm-10">
        {% block content %}
        {% endblock content %}

        {% block pagination %}
          {% if is_paginated %}
            <div class="pagination">
              <span class="page-links">
                {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}
                <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
                {% endif %}
              </span>
            </div>
          {% endif %}
        {% endblock pagination %}
      </div>
    </div>
  </div>
</body>
</html>

templates/book_detail.html
{% extends 'base_generic.html' %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p>
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong>
    {% for genre in book.genre.all %}
      {{ genre }}{% if not forloop.last %},{% endif %}
    {% endfor %}
  </p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
      {% if copy.status != 'a' %}
        <p>
          <strong>Due to be returned:</strong> {{ copy.due_back }}
        </p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>ID:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock content %}

templates/book_list.html
{% extends 'base_generic.html' %}

{% block content %}
  <h1>Book List</h1>
  {% if my_book_list %}
    <ul>
      {% for book in my_book_list %}
        <li>
          <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}
{% endblock content %}

templates/catalog/bookinstance_list_borrowed_user.html
{% extends 'base_generic.html' %}

{% block content %}
  <h2>Borrowed books</h2>

  {% if bookinstance_list %}
    <ul>
      {% for bookinst in bookinstance_list %}
        <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
          <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no books borrowed.</p>
  {% endif %}
{% endblock content %}

templates/index.html
{% extends 'base_generic.html' %}

{% block content %}
  <h1>Local Library Home</h1>
  <p>
    Welcome to LocalLibrary, a website developed by <em>Mozilla Developer Network</em>!
  </p>
  <h2>Dynamic content</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_avaliable }}</li>
    <li><strong>Author:</strong> {{ num_authors }}</li>
    <li><strong>Science Fiction:</strong> {{ num_genres }}</li>
  </ul>

  <p>You have visited this page {{ num_visits }} {% if num_visits == 1 %} time {% else %} times{% endif %}. </p>
{% endblock content %}